#!/usr/bin/env python    
def sum_function(n):
    try:
        return sum(range(n + 1))
    except TypeError:
        print "That's no number lad"
    finally:
        print "Don't mind getting an exception, I will get printed no matter what!"
if __name__ == '__main__':
    print sum_function(5)
    sum_function('a')
